
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Product</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<form action="Index.php?a=insert&c=product" method="POST">
		<div class="add">
			<div>Product</div>
			<div class="cancel">
				<button><a href="Index.php?a=grid&c=product">Cancel</a></button>
			</div>
			<div class="submit">
				<button type="submit" value="submit">Submit</button>
			</div>
		</div>
		<div>Product Information</div>
		<table>
			<tr>
				<td>Name</td>
				<td><input type="text" name="name" value=""></td>
			</tr>
			<tr>
				<td>SKU</td>
				<td><input type="text" name="sku" value=""></td>
			</tr>
			<tr>
				<td>Cost</td>
				<td><input type="text" name="cost" value=""></td>
			</tr>
			<tr>
				<td>Price</td>
				<td><input type="text" name="price" value=""></td>
			</tr>
			<tr>
				<td>Quentity</td>
				<td><input type="text" name="quentity" value=""></td>
			</tr>
			<tr>
				<td>Description</td>
				<td> <input type="text" name="description"> </td>
			</tr>
			<tr>
				<td>Status</td>
				<td>
					<select name="status">
						<option value = "0">0</option>
                        <option value = "1">1</option>
					</select>
				</td>
			</tr>
		</table>
	</form>
</body>
</html>